##########################################################
#                        Variables                       #
#                                                        #
#   $player$ - The players name                          #
#   $nextLevel$ - Next Level                             #
#   $name$ - The (Pickaxe / Sword) leveled up            #
#   $newLevel (currentLevel)$ - The players level        #
#   $nextXP$ - The XP required for the next level        #
#   $currentXp (xp)$ - The players current XP            #
#                                                        #
##########################################################

level-up-message:
- '&e&l&n-----------[ &a&lLevel Up &e&l&n ]----------'
- '&e&l$player$! You have leveled up to $newLevel$ in $name$.'
- '&e&lNext Level: $nextLevel$'
- '  &a&lXP needed: $nextXP$'
- '&e&l&n-----------[ &a&lLevel Up &e&l&n ]----------'
##
## {name} - name in picks/swords.yml
## {level} - item level
## {xp} - item xp
## {blocks} - blocks broken (only for picks ofc)
##
pick-display-name: "{name} | Level: {level} | Xp: {xp}/{nextLevelXpTotal} | Next Level in: {xpDiff} | Blocks Broken: {blocks}"
sword-display-name: "{name} | Level: {level} | Xp: {xp}/{nextLevelXpTotal} | Next Level in: {xpDiff}"
cosmetics:
  firework:
    #Does each level control the firework effect? Set to true for in-depth management
    determinePerLevel: false
    #The maximim amount of Fireworks that can be launched
    #Set to RANDOM-MIN:3&MAX:7 to randomize between 3 and 7 (you can, of course, use any number)
    amount: 1
    #Display to only the player?
    playerOnly: true
    #If 'playerOnly` is false, this is the effective range to display the firework in
    #IE If a player is within the range from the player, they too will see the firework.
    range: 10
    #The colors of the firework itself
    #No more than 5
    colors:
    - BLUE
    - YELLOW
    - RANDOM
    #When the firework is fading out, what colors are shown?
    #No more than 5
    fade-colors:
    - RED
    - GREEN
    #Leave a trail of sparkles?
    trail: false
    #Fade into the darkness
    flicker: false
    #The Effect of the Firework (or Shape)
    #Allowed: BALL, BALL_LARGE, STAR, CREEPER, BURST
    type: BALL
    #If 'deteminePerLevel' is false, these are levels which will not display effects.
    #Leave it empty if you want all levels to have effects.
    blacklist:
    - 1
    - 2
    - 3
    - 4
