name: ${plugin.name}
version: ${version}
main: ${plugin.mainClass}
depend: [WorldGuard]
commands:
  pick:
    description: Opens up your pick UI. Use points arg to spend points on this item.
    usage: /<command> points/level [amount]
  sword:
    description: Opens up your sword UI. Use points arg to spend points on this item.
    usage: /<command> points/level [amount]
  pgive:
    description: Give a new enhanced pick or sword to a player.
    usage: /<command> [pick/sword] [config name] [player]
    permission: pickaxes.admin
    aliases: [givepick, givesword, pitem]
  ppoints:
    description: Give points to a player to spend on picks/swords.
    usage: /<command> give [player] [points]
    permission: pickaxes.admin
permissions:
  pickaxes.*:
    description: Gives access to all enhanced pickaxes commands.
    children:
      pickaxes.admin: true
      pickaxes.multiplier: true
  pickaxes.admin:
    description: Allows to give enhanced item to player.
    default: op
  pickaxes.multiplier:
    description: Multiplier permission
    default: op
